config/routes.rb
Rails.application.routes.draw do
  root to: "web_pages#index"
  
  resources :web_pages, :comments
end

app/models/web_page.rb
class WebPage < ActiveRecord::Base

  validates_uniqueness_of :full_url
  validates_uniqueness_of :shortened_url
  ##TODO Validate url

  before_save :shorten_url


  private

  def shorten_url
    self.shortened_url = SecureRandom.hex(2)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :set_access_control_headers

  def index
    @web_page = WebPage.find_or_create_by full_url: params[:web_page]
    render :json => @web_page.to_json
  end

  private

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Max-Age'] = "1728000"
  end
end

app/controllers/web_pages_controller.rb
class WebPagesController < ApplicationController
  def index
    @web_pages = WebPage.all
  end

  def create
    @web_page = WebPage.new(params[:web_page].permit(:full_url))
    if @web_page.save
      flash[:success] = "Link created!"
    else
      flash[:error] = @web_page.errors.empty? ? "Error" : @web_page.errors.full_messages.to_sentence
    end
    redirect_to web_pages_path
  end

  def show
    @web_page = WebPage.find_by_shortened_url(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Annotate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/web_pages/index.html.erb
<%= form_for WebPage.new do |f| %>
  <%= f.label :full_url %>
  <%= f.text_field :full_url %>
  <%= f.submit %>
<% end %>

<% @web_pages.each do |web_page|%>

  <%= link_to web_page.full_url %> | <%= link_to web_page_url(web_page.shortened_url), web_page_url(web_page.shortened_url) %>
  <br>

<% end %>

app/views/web_pages/show.html.erb
Full url: <%= @web_page.full_url %>
<br>Shortened url: <%= web_page_url(@web_page.shortened_url) %>

<iframe src="<%= @web_page.full_url %>">
</iframe>